### ISSUE TITLE
CN FINAL FANTASY XIV  does not exist

### ISSUE THREAD

**Issue by Clulu1499** [blhutchings/AutoTriadBuddy#1]
![CNXIV](https://user-images.githubusercontent.com/72173120/169917778-be50dd5e-8457-4ed2-8be3-b07cca733e18.png)
If possible please add <最终幻想XIV> appname

**Comment by blhutchings** [comment]
Ok, removed the unicode restriction. Should be good now, please let me know if you have any more issues :)
